services:
  backend:
    image: backend:${APP_VERSION}
    build:
      context: ./backend
      args:
        BACKEND_PORT: ${BACKEND_PORT}
    container_name: my-backend
    networks:
      proxy-network:
          ipv4_address: 172.20.3.20
    env_file:
       - .env

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
    ports:
      - "80:80"
    volumes: #двустадийная с запуском скрипта entrypoint кастомизации порта
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - ./nginx/entrypoint.sh:/entrypoint.sh
    depends_on:
      backend:
        condition: service_healthy
    networks:
      proxy-network:
        ipv4_address: 172.20.3.10
    env_file:
      - .env
    entrypoint: ["/entrypoint.sh"]

networks:
  proxy-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16